#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


grunt
RETVAL=$?

[ $RETVAL -eq 0 ] && echo Success
[ $RETVAL -ne 0 ] && echo Failure

if [ $RETVAL -ne 0 ]
then
	echo "Grunt tests failed: commit prevented"
	exit 1
else
	echo "grunt passed > commit enabled"
	git push local
	echo " + pushed to local git repo"
	exit 0
fi